pipeline {
    agent any
    environment {
        LIQUIBASE_LICENSE_KEY = credentials('LIQUIBASE_LICENSE_KEY')
        LIQUIBASE_COMMAND_URL = "jdbc:postgresql://localhost:5432/dev"
        LIQUIBASE_COMMAND_CHANGELOG_FILE = "changelog-root.xml"
        LIQUIBASE_SEARCH_PATH = "/database"
        LB_FLOW_ENV = "dev"
    }
    stages {
        stage("Precheck") {
            steps {
                sh 'echo "Current PATH: $PATH"'
                sh 'java -version'
            }
        }
        stage("Liquibase") {
            steps {
                sh 'echo ***** Run flow file Jenkinsfile_ci *****'
                withCredentials([
                    usernamePassword(
                        credentialsId: 'whateverID', 
                        usernameVariable: 'LIQUIBASE_COMMAND_USERNAME', 
                        passwordVariable: 'LIQUIBASE_COMMAND_PASSWORD'
                    )
                ]) {
                    sh 'echo ***** Run flow file *****'
                    sh 'liquibase flow'
                }
            }
        }
    }
    post {
        always {
            sh 'echo ***** Clean up workspace *****'
            deleteDir()
        }
    }
}